// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STCA_DataLayer;

namespace STCA_DataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220718005745_seed-data")]
    partial class seeddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("STCA_DataLayer.TipoAreaAcceso", b =>
                {
                    b.Property<int>("TipoAreaAccesoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TipoAreaAccesoId");

                    b.ToTable("TiposAreasAcceso");

                    b.HasData(
                        new
                        {
                            TipoAreaAccesoId = 1,
                            Nombre = "Oficina"
                        },
                        new
                        {
                            TipoAreaAccesoId = 2,
                            Nombre = "Estacionamiento"
                        },
                        new
                        {
                            TipoAreaAccesoId = 3,
                            Nombre = "Area Deportiva"
                        },
                        new
                        {
                            TipoAreaAccesoId = 4,
                            Nombre = "Edificio Principal"
                        },
                        new
                        {
                            TipoAreaAccesoId = 5,
                            Nombre = "Area Administrativa"
                        },
                        new
                        {
                            TipoAreaAccesoId = 6,
                            Nombre = "Tipo de Area 1"
                        },
                        new
                        {
                            TipoAreaAccesoId = 7,
                            Nombre = "Tipo de Area 2"
                        },
                        new
                        {
                            TipoAreaAccesoId = 8,
                            Nombre = "Tipo de Area 3"
                        },
                        new
                        {
                            TipoAreaAccesoId = 9,
                            Nombre = "Tipo de Area 4"
                        },
                        new
                        {
                            TipoAreaAccesoId = 10,
                            Nombre = "Tipo de Area 5"
                        },
                        new
                        {
                            TipoAreaAccesoId = 11,
                            Nombre = "Tipo de Area 6"
                        },
                        new
                        {
                            TipoAreaAccesoId = 12,
                            Nombre = "Tipo de Area 7"
                        },
                        new
                        {
                            TipoAreaAccesoId = 13,
                            Nombre = "Tipo de Area 8"
                        },
                        new
                        {
                            TipoAreaAccesoId = 14,
                            Nombre = "Tipo de Area 9"
                        },
                        new
                        {
                            TipoAreaAccesoId = 15,
                            Nombre = "Tipo de Area 10"
                        },
                        new
                        {
                            TipoAreaAccesoId = 16,
                            Nombre = "Tipo de Area 11"
                        },
                        new
                        {
                            TipoAreaAccesoId = 17,
                            Nombre = "Tipo de Area 12"
                        },
                        new
                        {
                            TipoAreaAccesoId = 18,
                            Nombre = "Tipo de Area 13"
                        },
                        new
                        {
                            TipoAreaAccesoId = 19,
                            Nombre = "Tipo de Area 14"
                        },
                        new
                        {
                            TipoAreaAccesoId = 20,
                            Nombre = "Tipo de Area 15"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
